### ISSUE TITLE
update request to axios or got 

### ISSUE THREAD

**Issue by pejman1** [josephsurin/su-downloader3#13]
Hello
do you have any intention to update this incredible package with axios or got library

**Comment by josephsurin** [comment]
Hi. Thanks for your interest but I don't use this in any of my other projects and am not actively maintaining it (happy to review and merge PRs). Check out [these](https://github.com/sonnyp/aria2.js) [projects](https://github.com/hgouveia/node-downloader-helper), they are actively maintained and might be good alternatives.
