### ISSUE TITLE
non of the examples and the engine works correctly on mac os

### ISSUE THREAD

**Issue by pejman1** [josephsurin/su-downloader3#5]
Hello.
I am writing to inform you that I've tested you downloader engine and it doesn't work currently in mac os
I have test all of examples non of them work correctly 
while you set thread for example to 3 . it start downloading three instance of a file and then merge all of them together . all file all same. for example a 5mg download file would be a 15 or maybe more!! and the ultimate file will be damaged . 

observer also does not work correctly. after finishing download it shows wrong percentage and numbers

**Comment by josephsurin** [comment]
The examples are working fine for me running on Arch Linux. I can't test for macOS as I don't have a MacBook, sorry.
